import { describe, it, expect, vi, beforeEach } from 'vitest';
import { IngestionService } from '../lib/ingestionService';
import { geminiClient } from '../lib/gemini';
import JSZip from 'jszip';

describe('IngestionService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should correctly extract files and call Gemini for analysis', async () => {
    // 1. Create a mock ZIP
    const zip = new JSZip();
    zip.file('README.md', '# Test Project\nThis is a test.');
    zip.file('package.json', JSON.stringify({ name: 'test-project', dependencies: { react: '18.0.0' } }));
    
    const content = await zip.generateAsync({ type: 'nodebuffer' });

    // 2. Mock Gemini response
    const mockAiResponse = JSON.stringify({
      title: 'AI Test Project',
      tagline: 'A tagline generated by AI',
      description: 'A full description generated by AI.',
      category: 'AI',
      type: 'Web App',
      techStack: ['React', 'Next.js'],
      architecture: 'Monolithic',
      marketIntel: 'High potential',
      suggestedBudget: '$10k',
      suggestedTimeline: '2 months'
    });

    vi.mocked(geminiClient.generateContent).mockResolvedValue(mockAiResponse);

    // 3. Execute ingestion
    const result = await IngestionService.ingestZip(content);

    // 4. Assertions
    expect(result.title).toBe('AI Test Project');
    expect(result.techStack).toContain('React');
    expect(geminiClient.generateContent).toHaveBeenCalled();
    
    // Check if context was sent (simple check if prompt contains README content)
    const promptArg = vi.mocked(geminiClient.generateContent).mock.calls[0][0];
    expect(promptArg).toContain('README.md');
    expect(promptArg).toContain('test-project');
  });

  it('should throw an error if Gemini fails', async () => {
    const zip = new JSZip();
    zip.file('README.md', 'test');
    const content = await zip.generateAsync({ type: 'nodebuffer' });

    vi.mocked(geminiClient.generateContent).mockRejectedValue(new Error('AI Error'));

    await expect(IngestionService.ingestZip(content)).rejects.toThrow('Failed to analyze project with AI');
  });
});
