'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'SK' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

const translations = {
  SK: {
    common: {
      projects: 'PROJEKTY',
      content_ai: 'CONTENT AI',
      about: 'O NÁS',
      contact: 'KONTAKT',
      scale: 'SCALE_RESOURCES',
      production: 'PRODUKCIA',
      stable: 'STABILNÁ',
    },
    seo: {
      title: 'LARSEN EVANS PROJECTS',
      description: 'Elitná prehliadka prémiových PWA a AI riešení od LARSEN EVANS',
    },
    tickers: {
      connected: 'LARSEN_EVANS_CORE_PRIPOJENÝ',
      active: 'SYNAPSE_STREAM_v4.5_AKTÍVNY',
      analysis: 'ELITNÁ_ANALÝZA_SEKTORA',
      data_lock: 'PROPRIETÁRNY_DÁTOVÝ_ZÁMOK',
      filter: 'NEURÁLNY_FILTER_LE_v1.0'
    },
    repository: {
      categories: 'KATEGÓRIE / FILTER',
      all: 'VŠETKO',
      syncing: 'SYNCHRONIZÁCIA DÁT...',
      results: 'VÝSLEDKY / INDEX v5.2',
      sector_total: 'CELKOVO V SEKTORE',
      no_results: 'Nenašli sa žiadne dátové sekvencie',
      no_results_desc: 'AKTUÁLNY FILTRAČNÝ KOEFICIENT "{category}" VRACIA PRÁZDNE VYFRUOVACIE VYMEDZENIA. UPRAVTE PARAMETRE PRE SYNCHRONIZÁCIU.',
      reset: 'RESETOVAŤ PARAMETRE',
      live_feed: 'LIVE_FEED / v5.2',
      buffer: 'BUFFER',
      engine: 'ENGINE',
      seq_year: 'SEKVENCIA / ROK',
      contract_client: 'KONTRAKT / KLIENT'
    },
    enterprise: {
      tagline: 'LARSEN ENTERPRISE v5.0',
      proprietary: 'AKTÍVNA PROPRIETÁRNA ARCHITEKTÚRA',
      heading: 'ŠKÁLUJTE \n ZA HRANICE.',
      description: 'Inteligentné podnikové riešenia a AI-driven infraštruktúra talentov pre organizácie s vysokou dynamikou.',
      strategy_title: 'AI STRATÉGIA',
      strategy_desc: 'End-to-end stratégie automatizácie využívajúce architektúru LARSEN-SYNTH.',
      elite_title: 'ELITNÝ VÝBER',
      elite_desc: 'AI-preverený pool talentov optimalizovaný pre nasadenie v podnikovom meradle.',
      secure_title: 'ZABEZPEČENÁ INFRA',
      secure_desc: 'Bezpečnostné protokoly vojenskej úrovne pre všetky AI integrované pracovné postupy.',
      global_title: 'GLOBÁLNY DOSAH',
      global_desc: 'Distribuované systémy navrhnuté pre škálovateľnosť vo viacerých regiónoch.',
      learn_more: 'Zistiť viac',
      new_feature: 'NOVÁ FUNKCIA',
      proposal_heading: 'AI PROPOSAL \n ENGINE.',
      proposal_desc: 'Generujte komplexné obchodné návrhy a architektonické plány za 30 sekúd.',
      access_alpha: 'Prístup k Alfe',
      market_intel: 'TRHOVÁ INTELIGENCIA',
      why_scale: 'PREČO ŠKÁLOVAŤ?',
      uptime: 'GARANTOVANÝ 99.9% UPTIME',
      architects: 'DEDIKOVANÍ ARCHITEKTI',
      realtime: 'VÝKON V REÁLNOM ČASE'
    },
    generator: {
      tagline: 'LARSEN EVANS SYNTHESIS v5.2',
      heading: 'CONTENT \n GENERATOR.',
      description: 'Elitný marketingový výstup pre globálne projekty, syntetizovaný proprietárnou architektúrou LARSEN s integráciou Gemini 1.5 Pro.',
      type_label: '01 / TYP OBSAHU',
      core_data: '02 / ZÁKLADNÉ DÁTA',
      project_title: 'Názov projektu',
      keywords: 'Cieľové kľúčové slová',
      placeholder_title: 'napr. BRUTALISTICKÁ VILA',
      placeholder_keywords: 'napr. BETÓN, MINIMALIZMUS, SKLO',
      synth_button: 'SYNTETIZOVAŤ...',
      generate_button: 'GENEROVAŤ DÁTA',
      footer_note: 'Využíva architektúru Gemini 1.5 Pro pre precíznu syntézu obsahu, sémantické mapovanie a štrukturálnu verifikáciu.',
      output_label: 'VÝSTUP / BUFFER / v5.2 / SYNC: AKTÍVNY',
      clone_data: 'KLONOVAŤ DÁTA',
      copied: 'SKOPÍROVANÉ DO BUFFRU',
      awaiting: 'Čakanie na vstupnú sekvenciu',
      ready: 'Systém pripravený na syntézu dát',
      error_title: 'Chyba pri generovaní obsahu',
      error_desc: 'Skontrolujte API kľúč alebo skúste znova neskôr.',
      blog: 'Blogový článok',
      case_study: 'Case Study',
      social: 'Sociálne siete',
      marketing: 'Marketingový text',
      blog_prompt: 'Napíš pútavý blogový článok o projekte',
      case_study_prompt: 'Vytvor detailnú prípadovú štúdiu pre projekt',
      social_prompt: 'Vygeneruj príspevky na Instagram, LinkedIn a Facebook pre',
      marketing_prompt: 'Vytvor predajný text pre webovú stránku o',
      prompt_suffix: 'Formátuj v Markdown. Použi štruktúrované nadpisy a zoznamy.',
      keywords_label: 'Kľúčové slová:'
    },
    detail: {
      return: 'INDEX / SPÄŤ',
      system_stable: 'SYSTÉM_STABILNÝ',
      overview: 'ANALÝZA / PREHĽAD',
      deploy: 'SPUSTIŤ DEPLOY',
      enhance_vision: 'ROZŠÍRENÝ REŽIM VIDENIA',
      intel: 'PROJEKTOVÝ INTEL',
      ident_client: 'KLIENT / ENTITA',
      sector_cat: 'SEKTOR / KATEGÓRIA',
      mech_type: 'MECHANIZMUS / TYP',
      tx_timestamp: 'TIMESTAMP / ROK',
      encryption: 'ENKRYPCIA DÁT',
      verification_note: 'Všetky projektové dáta sú overené AI protokolom Larsen Evans.',
      neural_intel: 'NEURÁLNA INTELIGENCIA',
      stack_intelligence: 'STACK INTELLIGENCE',
      arch_neural_map: 'ARCHITEKTÚRA / MAPA',
      market_potential: 'TRHOVÝ POTENCIÁL',
      view_presentation: 'SPUSTIŤ PREZENTÁCIU',
      not_found: 'Projekt nebol nájdený',
      back_to_list: 'Späť na zoznam projektov',
      arch_analysis: 'ARCHITEKTONICKÁ ANALÝZA',
      security_audit: 'BEZPEČNOSTNÝ AUDIT',
      sync_protocol: 'SYNCHRONIZAČNÝ PROTOKOL',
      budget: 'ROZPOČET / ODPORÚČANÝ',
      timeline: 'TIMELINE / ODHAD',
      documentation: 'DOKUMENTÁCIA PROJEKTU',
      available_languages: 'DOSTUPNÉ JAZYKY',
      docs_desc: 'Dokumentácia pre {title} je dostupná vo viacerých jazykoch. Vyberte si preferovaný jazyk vyššie.'
    },
    ai_tools: {
      language: 'JAZYK',
      search_assistant: 'ASISTENT VYHĽADÁVANIA',
      neural_engine: 'SÉMANTICKÝ NEURÁLNY ENGINE :: STATUS_AKTÍVNY',
      query_placeholder: 'MOLEKULÁRNY VSTUP DOPYTU / ZADAJTE PARAMETRE...',
      execute: 'VYKONAŤ',
      syncing: 'SYNCHRONIZÁCIA',
      neural_suggestions: 'NEURÁLNE NÁVRHY',
      suggestions_fallback: ['MODERNÉ PWA', 'E-COMMERCE API', 'AI ENGINE', 'MOBILNÉ CORE', 'BLOCKCHAIN HUB'],
      logic_overrides: 'LOGICKÉ PREPÍSANIA',
      market_analyzer: 'SYSTÉMOVÁ ANALÝZA',
      market_intel: 'TRHOVÁ INTELIGENCIA / CORE V4.0',
      sector_selection: 'VÝBER CORE SEKTORA',
      insight_data: 'ÚDAJE O VHĽADE',
      volume_demand: 'OBJEM / DOPYT',
      valuation_price: 'OCEŇOVANIE / CENA',
      strategic_vectors: 'STRATEGICKÉ VEKTORY',
      alpha_ops: 'ALPHA OPERÁCIE',
      reevaluate: 'PREHODNOTIŤ TRH',
      export_raw: 'EXPORTOVAŤ RAW DÁTA',
      system_standby: 'SYSTÉM V POHOTOVOSTI',
      revenue_optimizer: 'OPTIMALIZÁCIA VÝNOSOV',
      revenue_desc: 'AI-poháňaná analýza na maximalizáciu výnosového potenciálu vašej platformy',
      optimization_strategy: 'STRATÉGIA OPTIMALIZÁCIE',
      optimizing_msg: 'Optimalizácia výnosovej stratégie...',
      revenue_overview: 'PREHĽAD VÝNOSOV',
      current_revenue: 'AKTUÁLNY VÝNOS',
      potential_revenue: 'POTENCIÁLNY VÝNOS',
      revenue_increase: 'NÁRAST VÝNOSOV',
      optimization_areas: 'OBLASTI OPTIMALIZÁCIE',
      top_recommendations: 'TOP ODPORÚČANIA',
      implementation_steps: 'KROKY IMPLEMENTÁCIE',
      re_optimize: 'PRE-OPTIMALIZOVAŤ',
      export_plan: 'EXPORTOVAŤ PLÁN',
      ai_assistant: 'AI_ASISTENT / v5.2',
      revenue_optimizer_title: 'OPTIMALIZÁTOR VÝNOSOV',
      active_analysis: 'AKTÍVNA_ANALÝZA',
      mapping_msg: 'Syntetickí agenti momentálne mapujú trhové premenné a výnosové toky pre túto konkrétnu architektonickú sekvenciu.',
      core_sync_ready: 'CORE_SYNCHRONIZÁCIA_PRIPRAVENÁ',
      query_assistant: 'ASISTENT DOPYTU',
      suggestions_prompt: 'Generuj 5 krátkych profesionálnych návrhov na vyhľadávanie pre platformu trhoviska projektov. Príklady: "Moderná PWA", "Next.js API", "AI Dashboard". Vráť ako JSON pole reťazcov.',
      enhance_prompt: 'Vylepši tento dopyt na vyhľadávanie pre vysoko presné párovanie projektov: "{searchQuery}". Kontext: {context}. Vráť iba vylepšený dopyt.',
      analyzer_prompt: 'Analyzuj aktuálne trendy na trhu pre {category} projekty. Zameraj sa na: 1. Vzorce dopytu a oblasti rastu, 2. Cenové trendy a očakávania rozpočtu, 3. Najžiadanejšie zručnosti a technológie, 4. Vzorce časovej osi projektov, 5. Regionálne rozdiely na trhu, 6. Vznikajúce príležitosti. Poskytni realizovateľné poznatky pre platformu trhoviska projektov. Vráť štruktúrované dáta so špecifickými odporúčaniami.',
      fallback_demand: 'Vysoký dopyt po vývoji webových aplikácií a AI projektoch',
      fallback_pricing: 'Priemerný rozpočet projektu: 5000 - 15000 €',
      fallback_rec1: 'Zamerajte sa na AI a projekty strojového učenia',
      fallback_rec2: 'Cielte na projekty so stredným rozpočtom (5k - 15k €)',
      fallback_rec3: 'Zvýraznite projekty s jasnými časovými osami',
      fallback_rec4: 'Zdôraznite služby zabezpečenia kvality (QA)',
      fallback_opp1: 'Riešenia pre prácu na diaľku',
      fallback_opp2: 'Optimalizácia e-commerce',
      fallback_opp3: 'Vývoj mobilných aplikácií',
      fallback_opp4: 'Služby migrácie do cloudu',
      cat_all: 'všetko',
      cat_web: 'vývoj webu',
      cat_mobile: 'mobilné aplikácie',
      cat_ai: 'ai a ml',
      cat_ecommerce: 'e-commerce',
      cat_automation: 'automatizácia biznisu',
      strat_complete: 'Kompletná optimalizácia výnosov',
      strat_pricing: 'Cenová stratégia',
      strat_commission: 'Optimalizácia provízií',
      strat_upselling: 'Príležitosti na upselling',
      strat_retention: 'Retencia zákazníkov',
      revenue_optimizer_hero: 'OPTIMALIZÁTOR VÝNOSOV',
      revenue_optimizer_tagline: 'AI-POHÁŇANÁ ANALÝZA FINANČNEJ TRAJEKTÓRIE',
      awaiting_ingestion: 'ČAKANIE NA INGESTIU DÁT...',
      impact_label: 'DOPAD',
      standard_label: 'ŠTANDARD',
      optimized_label: 'OPTIMALIZOVANÉ',
      critical_label: 'KRITICKÉ',
      high_load_label: 'VYSOKÁ ZÁŤAŽ',
      cat_devops_fintech: 'DevOps / Fintech',
      cat_blockchain_ai: 'Blockchain / AI',
      cat_travel_ai: 'Travel / AI',
      cat_gaming: 'Gaming',
      cat_fintech_ai_biz: 'Fintech / AI / Biznis',
      cat_innovation: 'Inovácie',
      cat_messaging_privacy: 'Messaging / Súkromie',
      cat_ai_devops: 'AI / DevOps'
    },
    finstat: {
      live_production: 'B2B SaaS Softvér | Live na produkcii',
      company_search: 'Vyhľadávač firiem',
      v4_region: 'pre celý región V4',
      what_selling: 'Čo vlastne predávame?',
      selling_desc: 'Softvér, do ktorého firmy zadajú IČO svojho partnera a do 1 sekundy vidia: kto ho reálne vlastní, či nemá skryté dlhy a či nie je prepojený na podvodníkov.',
      aggregation: 'Agregujeme štátne registre Slovenska, Česka, Poľska a Maďarska do jedného kliknutia.',
      show_how: 'Ukázať ako to funguje',
      what_system_does: 'Čo presne náš systém robí?',
      scrape_registers: '1. Vykráda 4 Registre',
      scrape_desc: 'Už žiadne ručné hľadanie v ORSR, ARESe, či KRS. My tie dáta sťahujeme automaticky do jednej databázy.',
      draw_spiders: '2. Kreslí "Pavúkov"',
      draw_desc: 'Namiesto čítania výpisov vygenerujeme interaktívny graf. Okamžite vidíte prepojenie na schránkové firmy.',
      erp_conn: '3. Napojenie na ERP',
      erp_desc: 'Napojíme sa na ERP klienta. Ak dodávateľ prestane platiť, náš systém pošle okamžité varovanie.',
      zero_dev_risk: 'Proof of Stability: Nulové Dev Riziko',
      tech_not_on_paper: 'Technológia nie je na papieri, je nasadená v produkcii.',
      qa_tests: 'Úspešných QA Testov',
      code_coverage: 'Pokrytie kódu 85%+ testami',
      unfair_advantage: 'Unfair Advantage',
      typo_alg: 'Algoritmus spája identity vo V4 aj pri preklepoch.',
      infra: 'Infraštruktúra',
      scalable_now: 'PostgreSQL, Redis cache. Škálovateľné ihneď.',
      erp_gem: 'ERP Integrácie: Enterprise Klenot',
      erp_deeper: 'Verejné registre neobsahujú všetko. V4-Finstat ide hlbšie vďaka napojeniu na účtovníctvo.',
      real_time_payments: 'Analýza platieb v reálnom čase',
      cash_flow_tracking: 'Platí partner faktúry včas? Sledujeme cash-flow a záväzky.',
      auto_webhooks: 'Automatické varovania (Webhooks)',
      risk_score_alert: 'Notifikácia, ak sa zhorší risk score kľúčového dodávateľa.',
      ready_connectors: 'Pripravené konektory',
      implementation_hours: 'Implementácia trvá hodiny. Vytvárame enormné "switching costs".',
      business_model: 'Biznis Model & Ziskovosť',
      high_margin: 'B2B SaaS s vysokou maržou a minimálnymi nákladmi.',
      pro_plan: 'PRO',
      medium_firms: 'Pre stredné firmy',
      biggest_growth: 'Najväčší rast',
      logistics: 'Pre logistiku',
      transactional: 'Transakčný model',
      banks_insurance: 'Pre Banky & Poisťovne',
      op_margin: 'Prevádzková Marža',
      target_arr: 'Cieľové ARR (Rok 2)',
      est_churn: 'Odhadovaný Churn',
      legal_compliance: 'Legal & Compliance',
      bulletproof: 'Bulletproof Compliance',
      gdpr_interest: 'GDPR & Oprávnený záujem',
      gdpr_desc: 'Zber dát je chránený čl. 6(1)(f) GDPR. Máme implementované "Právo na výmaz".',
      fair_use: 'Fair Use & Bezpečnosť',
      fair_use_desc: 'Scraping engine využíva rotujúce proxy. Nepreťažujeme štátne servery.',
      disclaimer: 'Automatický Disclaimer',
      disclaimer_desc: 'Každý graf cituje zdroje. Vylúčenie našej právnej zodpovednosti za dáta.',
      legal_title: '100% Legal & Zero Risk',
      agressive_growth: 'V4-Finstat je navrhnutý tak, aby agresívne rástol, no právne bol nedotknuteľný.',
      clean_table: 'Implementovali sme kompletný systém na mieru. Pri investícii preberáte čistý stôl.',
      roadmap: '12-Mesačná Roadmapa',
      series_a: 'Series A Dominance',
      investment_ask: 'Investičná požiadavka',
      potential_10x: 'Potenciál: 10x do 3 rokov',
      series_a_val: 'Podiel v technológii pre Series A s valuáciou 15M €',
      ready_product: 'Hotový Produkt',
      investment_sales: 'Investícia nejde do vývoja. Ide čisto do predaja a rýchleho znásobenia tržieb.',
      scalable_monopoly: 'Škálovateľný Monopol',
      cross_border_monopoly: 'Vytvárame neohrozený monopol na cezhraničnú risk analýzu.',
      live_demo_btn: 'Prejsť k Live Demonštrácii',
      enterprise_ready: 'Enterprise Ready',
      q1_title: 'Launch & Traction',
      q1_desc: '0-3 mes. Prvých 10 B2B kontraktov.',
      q2_title: 'V4 Expansion',
      q2_desc: '4-6 mes. Vstup na trh PL a HU.',
      q3_title: 'AI Intelligence',
      q3_desc: '7-9 mes. AI predikcie rizík partnera.',
      q4_title: 'Series A Dominance',
      q4_desc: '10-12 mes. Valuácia 15M+ EUR.'
    },
    home: {
      label: 'PROJEKTY / REPOZITÁR / V5.0',
      heading: 'INŽINIERING \n BUDÚCNOSTI \n <span className="text-silver">WEBU.</span>',
      description: 'SYSTEMATICKÁ ZBIERKA POKROČILÝCH WEBOVÝCH IMPLEMENTÁCIÍ A AI ARCHITEKTÚR, SYNTETIZOVANÁ PRE ELITNÝ VÝKON.',
      error_loading: 'Chyba pri načítaní projektov',
      error_desc: 'Skontrolujte pripojenie k internetu alebo API URL.'
    },
    projects_data: {
      v4_finstat_title: 'V4-Finstat',
      v4_finstat_tagline: 'Finančná Štardardizácia a Nasadenie',
      v4_finstat_desc: 'Štandardizácia Docker prostredí a menných priestorov pre spracovanie finančných dát.',
      v4_finstat_content: 'Tento projekt zahŕňal komplexnú Docker orchestráciu, štandardizáciu menných priestorov naprieč mikroslužbami a nastavenie automatizovaných nasadzovacích (deployment) potrubí pre prostredia VPS a Vercel.',
      v4_finstat_architecture: 'Mikroslužby so štandardizovaným menným priestorom a kontajnerizovanými nasadzovacími potrubiami.',
      v4_finstat_market_intel: 'Enterprise automatizácia zhody (compliance) s vysokým výnosovým potenciálom vo fintechu.',
      
      ico_atlas_title: 'ICO Atlas',
      ico_atlas_tagline: 'Kryptomenová Trhová Inteligencia',
      ico_atlas_desc: 'Komplexná sledovacia platforma pre počiatočné ponuky mincí a trhové trendy.',
      ico_atlas_content: 'Vyvinutý engine na spracovanie dát v reálnom čase pre sledovanie ICO, obsahujúci pokročilé grafy, analýzu sentimentu a investorské panely.',
      ico_atlas_architecture: 'Engine na spracovanie dát v reálnom čase s WebSocket aktualizáciami a potrubím na analýzu sentimentu.',
      ico_atlas_market_intel: 'Vysoký dopyt po krypto-informáciách; škálovateľný SaaS model.',
      
      booking_buddy_title: 'Booking Buddy',
      booking_buddy_tagline: 'AI Cestovný Asistent',
      booking_buddy_desc: 'Personalizované plánovanie ciest a optimalizácia rezervácií pomocou AI.',
      booking_buddy_content: 'Vytvorený inteligentný cestovný spoločník, ktorý optimalizuje ceny rezervácií a vytvára vlastné itineráre na základe preferencií používateľa a historických dát.',
      booking_buddy_architecture: 'Agentová architektúra riadená LLM pre plánovanie itinerárov a optimalizáciu cien.',
      booking_buddy_market_intel: 'Disruptívny potenciál v cestovnom ruchu; B2C predplatiteľský model.',
      
      dream_casino_title: 'The Dream Casino',
      dream_casino_tagline: 'Prémiový Herný Zážitok',
      dream_casino_desc: 'Luxusná online kasíno platforma zrekonštruovaná s dôrazom na UX and bezpečnosť.',
      dream_casino_content: 'Redizajnovaná celá cesta používateľa pre prémiový hazardný zážitok, integrujúca vysokovýkonné herné motory a robustné bezpečnostné protokoly.',
      dream_casino_architecture: 'Vysokovýkonný herný motor s integráciou zabezpečenej platobnej brány.',
      dream_casino_market_intel: 'Vysokokonverzná herná platforma zameraná na prémiový trh.',
      
      bizagent_title: 'BizAgent',
      bizagent_tagline: 'AI Business Assistant pre SZČO',
      bizagent_desc: 'Kompletné riešenie pre faktúry, výdavky and accounting špeciálne navrhnuté pre slovenský trh.',
      bizagent_content: 'BizAgent je inteligentný asistent pre malých podnikateľov. Ponúka automatické číslovanie faktúr, generovanie PAY by square QR kódov, OCR skenovanie bločkov s AI kategorizáciou výdavkov a exporty pre účtovníkov.',
      bizagent_architecture: 'Mikroslužby na Firebase s riadením stavu cez Riverpod a offline-first PWA synchronizáciou.',
      bizagent_market_intel: 'Zamerané na 600k+ SZČO na Slovensku s potenciálom pre automatizované účtovníctvo.',
      
      lumina_os_title: 'Lumina OS',
      lumina_os_tagline: 'Operačný Systém Novej Generácie',
      lumina_os_desc: 'Konceptualizácia OS zameraná na neurálne rozhrania a adaptívny dizajn UI.',
      lumina_os_content: 'Dizajnový a architektonický prieskum operačného systému, ktorý sa učí návyky používateľa a proaktívne ponúka relevantné nástroje a informácie.',
      lumina_os_architecture: 'Dizajn jadra zameraný na neurálne rozhrania s adaptívnou generáciou UI.',
      lumina_os_market_intel: 'Inovácia v okrajových prípadoch s dlhodobou hodnotou R&D.',
      
      betauthority_title: 'BetAuthority',
      betauthority_tagline: 'Hodnotenie kasín v celej Európe',
      betauthority_desc: 'Porovnávací nástroj pre online kasína a stávkové platformy s dátami v reálnom čase, výplatami a férovými podmienkami.',
      betauthority_content: 'BetAuthority je pokročilý dátami riadený porovnávací nástroj pre online kasína. Systém analyzuje viac ako 127 operátorov a poskytuje reálne informácie o dôveryhodnosti.',
      betauthority_architecture: 'Automatizovaná sieť na zoškrabovanie a verifikáciu dát pre audity stávkovania v reálnom čase.',
      betauthority_market_intel: 'Líder na trhu v transparentnosti a dôveryhodnosti založenej na dátach.',
      
      neon_bloom_messenger_title: 'Neon Bloom Messenger',
      neon_bloom_messenger_tagline: 'Prémiový komunikačný ekosystém',
      neon_bloom_messenger_desc: 'Vysokovýkonná platforma zameraná na súkromie postavená na protokole Matrix.',
      neon_bloom_messenger_content: 'Kompletná komunikačná infraštruktúra navrhnutá pre súkromie, rýchlosť a prémiovú estetiku. Postavené na Matrix protokole s Bun a React.',
      neon_bloom_messenger_architecture: 'Decentralizovaná infraštruktúra so šifrovaním E2EE a ultra-rýchlym API cez Bun.',
      neon_bloom_messenger_market_intel: 'Nika zameraná na súkromie s vysokým potenciálom rastu.',
      
      v4_finstat_v5_0_title: 'V4-Finstat v5.0',
      v4_finstat_v5_0_tagline: 'Enterprise Ready B2B SaaS',
      v4_finstat_v5_0_desc: 'SaaS softvér pre B2B monitoring firiem v regióne V4.',
      v4_finstat_v5_0_content: 'V4-Finstat v5.0 je enterprise riešenie pre B2B monitoring firiem. Integruje štátne registre SR, ČR, PL a HU do jedného kliknutia s interaktívnymi grafmi.',
      v4_finstat_v5_0_architecture: 'Enterprise-grade B2B SaaS architektúra s centralizovanou agregáciou dát z V4 registrov.',
      v4_finstat_v5_0_market_intel: 'Vysokomarginálny B2B SaaS, silný potenciál recyklovaných tržieb, nízky churn.',
      
      rubberduck_space_title: 'RubberDuck.Space',
      rubberduck_space_tagline: 'AI-Powered Autonómna Analýza a Oprava Kódu',
      rubberduck_space_desc: 'Platforma na autonómnu analýzu a opravu kódu pre moderné inžinierske tímy.',
      rubberduck_space_content: 'RubberDuck.Space je platforma riadená AI, ktorá poskytuje autonómnu analýzu a opravu kódu. Náš agent rozumie príčine problémov predtým, než navrhne opravy.',
      rubberduck_space_architecture: 'Agentová architektúra s rekurzívnou analýzou kódu a chirurgickými opravnými slučkami.',
      rubberduck_space_market_intel: 'AI oprava kódu pre podniky zameraná na 40%+ zníženie údržby technického dlhu.',
      rubberduck_space_arch_analysis: 'Viacúrovňová orchestrácia agentov s izolovanou verifikáciou v sandboxe a kryptografickými stopami.',
      rubberduck_space_security_audit: 'Tvrdené lokálne spracovanie dát s politikou nulového trénovania a plným sledovaním pôvodu.',
      rubberduck_space_budget: '50 tis. - 120 tis. €',
      rubberduck_space_timeline: '4-6 mesiacov',
      
      v4_finstat_arch_analysis: 'Precízne navrhnutá vrstva Docker orchestrácie s izolovanými sieťovými mennými priestormi.',
      v4_finstat_security_audit: 'Tvrdené obrazy kontajnerov s automatizovaným skenovaním zraniteľností v CI.',
      v4_finstat_budget: '15 tis. - 30 tis. €',
      v4_finstat_timeline: '2-3 mesiace',
      
      ico_atlas_arch_analysis: 'Vysokovýkonné spracovanie dátových tokov s distribuovaným škálovaním Postgresu.',
      ico_atlas_security_audit: 'Zabezpečené WebSocket protokoly s odstupňovaným riadením prístupu založenom na JWT.',
      ico_atlas_budget: '40 tis. - 75 tis. €',
      ico_atlas_timeline: '4-6 mesiacov',
      
      booking_buddy_arch_analysis: 'Samoopravné reťazce agentov s technikami rekurzívnej optimalizácie promptov.',
      booking_buddy_security_audit: 'Anonymizované spracovanie PII dát s prísnymi protokolmi obmedzovania frekvencie API.',
      booking_buddy_budget: '25 tis. - 50 tis. €',
      booking_buddy_timeline: '3-4 mesiace',
      
      dream_casino_arch_analysis: 'Architektúra riadená udalosťami s nízkou latenciou a synchronizáciou pod 10ms.',
      dream_casino_security_audit: 'Platobné úschovy s viacerými podpismi a distribuovaným monitorovaním proti podvodom.',
      dream_casino_budget: '60 tis. - 120 tis. €',
      dream_casino_timeline: '5-8 mesiacov',
      
      bizagent_arch_analysis: 'Vysokovýkonný CanvasKit renderer s robustným potrubím na extrakciu dát cez OCR.',
      bizagent_security_audit: 'Tvrdené bezpečnostné pravidlá s overeným nahrávaním súborov a šifrovaným PII.',
      bizagent_budget: '30 tis. - 70 tis. €',
      bizagent_timeline: '4-6 mesiacov',
      
      lumina_os_arch_analysis: 'Rust jadro s nulovou réžiou zamerané na sandboxované runtimy WebAssembly.',
      lumina_os_security_audit: 'Pamäťovo bezpečné prostredie pre spustenie s kryptografickými izolačnými vrstvami.',
      lumina_os_budget: '200 tis.+ €',
      lumina_os_timeline: '12-24 mesiacov',
      
      betauthority_arch_analysis: 'Distribuovaný scraping cluster s rozpoznávaním vzorov cez AI na obchádzanie detekcie auditov.',
      betauthority_security_audit: 'Šifrované databázové vrstvy s anonymizovanou knihou transakcií.',
      betauthority_budget: '45 tis. - 80 tis. €',
      betauthority_timeline: '4-6 mesiacov',
      
      neon_bloom_messenger_arch_analysis: 'Architektúra servera s nulovými znalosťami a distribuovanými dátovými črepmi cez MinIO.',
      neon_bloom_messenger_security_audit: 'Úplná implementácia Matrix E2EE s automatizovaným ukončením relácie.',
      neon_bloom_messenger_budget: '50 tis. - 90 tis. €',
      neon_bloom_messenger_timeline: '4-7 mesiacov',
      
      v4_finstat_v5_0_arch_analysis: 'Vysoko škálovateľný monitorovací systém s upozorneniami v reálnom čase a detekciou podvodov integrovanou v ERP.',
      v4_finstat_v5_0_security_audit: 'V súlade s GDPR s automatizovaným protokolovaním auditov a tvrdenou izoláciou dát.',
      v4_finstat_v5_0_budget: '50 tis. - 100 tis. €',
      v4_finstat_v5_0_timeline: '3-6 mesiacov'
    },
    ingestion: {
      tech_stack: 'Technologický Stack',
      architecture: 'Architektúra',
      market_intel: 'Market Intel',
      upload_zip: 'Nahrať ZIP (AI Analýza)',
      processing: 'Spracovávam ZIP...',
      analyzing: 'AI Analyzuje kódovú bázu...',
      success: 'Projekt úspešne načítaný',
      refine: 'Upraviť detaily',
      save: 'Uložiť do repozitára'
    }
  },
  EN: {
    common: {
      projects: 'PROJECTS',
      content_ai: 'CONTENT AI',
      about: 'ABOUT US',
      contact: 'CONTACT',
      scale: 'SCALE_RESOURCES',
      production: 'PRODUCTION',
      stable: 'STABLE',
    },
    seo: {
      title: 'LARSEN EVANS PROJECTS',
      description: 'Elite Showcase of Premium PWA and AI Solutions by LARSEN EVANS',
    },
    tickers: {
      connected: 'LARSEN_EVANS_CORE_CONNECTED',
      active: 'SYNAPSE_STREAM_v4.5_ACTIVE',
      analysis: 'ELITE_SECTOR_ANALYSIS',
      data_lock: 'PROPRIETARY_DATA_LOCK',
      filter: 'NEURAL_FILTER_LE_v1.0'
    },
    repository: {
      categories: 'CATEGORIES / FILTER',
      all: 'ALL',
      syncing: 'SYNCING DATA...',
      results: 'RESULTS / INDEX v5.2',
      sector_total: 'SECTOR TOTAL',
      no_results: 'No Data Sequences Found',
      no_results_desc: 'THE CURRENT FILTER COEFFICIENT "{category}" IS RETURNING EMPTY BUFFER STREAMS. ADJUST PARAMETERS FOR SYNCHRONIZATION.',
      reset: 'RESET BUFFER PARAMETERS',
      live_feed: 'LIVE_FEED / v5.2',
      buffer: 'BUFFER',
      engine: 'ENGINE',
      seq_year: 'SEQUENCE / YEAR',
      contract_client: 'CONTRACT / CLIENT'
    },
    enterprise: {
      tagline: 'LARSEN ENTERPRISE v5.0',
      proprietary: 'PROPRIETARY ARCHITECTURE ACTIVE',
      heading: 'SCALE \n BEYOND.',
      description: 'Intelligent enterprise solutions and AI-driven talent infrastructure for high-velocity organizations.',
      strategy_title: 'AI STRATEGY',
      strategy_desc: 'End-to-end automation strategies using LARSEN-SYNTH architecture.',
      elite_title: 'ELITE SELECTION',
      elite_desc: 'AI-vetted talent pool optimized for enterprise-scale deployments.',
      secure_title: 'SECURE INFRA',
      secure_desc: 'Military-grade security protocols for all AI-integrated workflows.',
      global_title: 'GLOBAL REACH',
      global_desc: 'Distributed systems designed for multi-region scalability.',
      learn_more: 'Learn More',
      new_feature: 'NEW FEATURE',
      proposal_heading: 'AI PROPOSAL \n ENGINE.',
      proposal_desc: 'Generate comprehensive business proposals and architecture blueprints in 30 seconds.',
      access_alpha: 'Access Alpha',
      market_intel: 'MARKET INTELLIGENCE',
      why_scale: 'WHY SCALE?',
      uptime: 'GUARANTEED 99.9% UPTIME',
      architects: 'DEDICATED ARCHITECTS',
      realtime: 'REAL-TIME PERFORMANCE'
    },
    generator: {
      tagline: 'LARSEN EVANS SYNTHESIS v5.2',
      heading: 'CONTENT \n GENERATOR.',
      description: 'Elite marketing output for global projects, synthesized by proprietary LARSEN architecture with Gemini 1.5 Pro integration.',
      type_label: '01 / CONTENT TYPE',
      core_data: '02 / CORE DATA',
      project_title: 'Project Title',
      keywords: 'Target Keywords',
      placeholder_title: 'e.g., BRUTALIST VILLA',
      placeholder_keywords: 'e.g., CONCRETE, MINIMAL, GLASS',
      synth_button: 'SYNTHESIZING...',
      generate_button: 'GENERATE DATA',
      footer_note: 'Utilizing Gemini 1.5 Pro architecture for high-fidelity content synthesis, semantic mapping, and structural verification.',
      output_label: 'OUTPUT / BUFFER / v5.2 / SYNC: ACTIVE',
      clone_data: 'CLONE DATA',
      copied: 'COPIED TO BUFFER',
      awaiting: 'Awaiting Input Sequence',
      ready: 'System ready for data synthesis',
      error_title: 'Content Generation Error',
      error_desc: 'Check API key or try again later.',
      blog: 'Blog Post',
      case_study: 'Case Study',
      social: 'Social Networks',
      marketing: 'Marketing Text',
      blog_prompt: 'Write an engaging blog post about the project',
      case_study_prompt: 'Create a detailed case study for the project',
      social_prompt: 'Generate Instagram, LinkedIn, and Facebook posts for',
      marketing_prompt: 'Create a selling text for a website about',
      prompt_suffix: 'Format in Markdown. Use structured headings and lists.',
      keywords_label: 'Keywords:'
    },
    detail: {
      return: 'INDEX / RETURN',
      system_stable: 'SYSTEM_STABLE',
      overview: 'ANALYSIS / OVERVIEW',
      deploy: 'EXECUTE DEPLOY',
      enhance_vision: 'ENHANCED VISION MODE',
      intel: 'PROJECT INTEL',
      ident_client: 'CLIENT / ENTITY',
      sector_cat: 'SECTOR / CATEGORY',
      mech_type: 'MECHANISM / TYPE',
      tx_timestamp: 'TIMESTAMP / YEAR',
      encryption: 'DATA ENCRYPTION',
      verification_note: 'All project data is verified by Larsen Evans AI protocol.',
      neural_intel: 'NEURAL INTELLIGENCE',
      stack_intelligence: 'STACK INTELLIGENCE',
      arch_neural_map: 'ARCH_NEURAL_MAP',
      market_potential: 'MARKET POTENTIAL',
      view_presentation: 'VIEW PRESENTATION',
      not_found: 'Project Not Found',
      back_to_list: 'Back to projects index',
      arch_analysis: 'ARCHITECTURAL ANALYSIS',
      security_audit: 'SECURITY AUDIT',
      sync_protocol: 'SYNC PROTOCOL',
      budget: 'BUDGET / SUGGESTED',
      timeline: 'TIMELINE / ESTIMATED',
      documentation: 'PROJECT DOCUMENTATION',
      available_languages: 'AVAILABLE LANGUAGES',
      docs_desc: 'Documentation for {title} is available in multiple languages. Select your preferred language above.'
    },
    ai_tools: {
      language: 'LANGUAGE',
      search_assistant: 'SEARCH ASSISTANT',
      neural_engine: 'SEMANTIC NEURAL ENGINE :: STATUS_ACTIVE',
      query_placeholder: 'MOLECULAR QUERY INPUT / ENTER PARAMETERS...',
      execute: 'EXECUTE',
      syncing: 'SYNCING',
      neural_suggestions: 'NEURAL SUGGESTIONS',
      suggestions_fallback: ['MODERN PWA', 'E-COMMERCE API', 'AI ENGINE', 'MOBILE CORE', 'BLOCKCHAIN HUB'],
      logic_overrides: 'LOGIC OVERRIDES',
      market_analyzer: 'SYSTEM ANALYSIS',
      market_intel: 'MARKET INTELLIGENCE / CORE V4.0',
      sector_selection: 'CORE SECTOR SELECTION',
      insight_data: 'INSIGHT DATA',
      volume_demand: 'VOLUME / DEMAND',
      valuation_price: 'VALUATION / PRICE',
      strategic_vectors: 'STRATEGIC VECTORS',
      alpha_ops: 'ALPHA OPS',
      reevaluate: 'REEVALUATE MARKET',
      export_raw: 'EXPORT RAW DATA',
      system_standby: 'SYSTEM STANDBY',
      revenue_optimizer: 'REVENUE OPTIMIZATION',
      revenue_desc: 'AI-powered analysis to maximize your platform\'s revenue potential',
      optimization_strategy: 'OPTIMIZATION STRATEGY',
      optimizing_msg: 'Optimizing revenue strategy...',
      revenue_overview: 'REVENUE OVERVIEW',
      current_revenue: 'CURRENT REVENUE',
      potential_revenue: 'POTENTIAL REVENUE',
      revenue_increase: 'REVENUE INCREASE',
      optimization_areas: 'OPTIMIZATION AREAS',
      top_recommendations: 'TOP RECOMMENDATIONS',
      implementation_steps: 'IMPLEMENTATION STEPS',
      re_optimize: 'RE-OPTIMIZE',
      export_plan: 'EXPORT PLAN',
      ai_assistant: 'AI_ASSISTANT / v5.2',
      revenue_optimizer_title: 'REVENUE_OPTIMIZER',
      active_analysis: 'ACTIVE_ANALYSIS',
      mapping_msg: 'Synthetic agents are currently mapping market variables and revenue streams for this specific architectural sequence.',
      core_sync_ready: 'CORE_SYNC_READY',
      query_assistant: 'QUERY ASSISTANT',
      suggestions_prompt: 'Generate 5 short professional search suggestions for a project marketplace platform. Examples: "Modern PWA", "Next.js API", "AI Dashboard". Return as a JSON array of strings.',
      enhance_prompt: 'Enhance this search query for high-fidelity project matching: "{searchQuery}". Context: {context}. Return enhanced query only.',
      analyzer_prompt: 'Analyze the current market trends for {category} projects. Focus on: 1. Demand patterns and growth areas, 2. Pricing trends and budget expectations, 3. Most in-demand skills and technologies, 4. Project timeline patterns, 5. Regional market differences, 6. Emerging opportunities. Provide actionable insights for a project marketplace platform. Return structured data with specific recommendations.',
      fallback_demand: 'High demand in web development and AI projects',
      fallback_pricing: 'Average project budget: $5000-15000',
      fallback_rec1: 'Focus on AI and machine learning projects',
      fallback_rec2: 'Target mid-range budget projects ($5k-15k)',
      fallback_rec3: 'Highlight projects with clear timelines',
      fallback_rec4: 'Emphasize quality assurance services',
      fallback_opp1: 'Remote work solutions',
      fallback_opp2: 'E-commerce optimization',
      fallback_opp3: 'Mobile app development',
      fallback_opp4: 'Cloud migration services',
      cat_all: 'all',
      cat_web: 'web development',
      cat_mobile: 'mobile apps',
      cat_ai: 'ai and ml',
      cat_ecommerce: 'e-commerce',
      cat_automation: 'business automation',
      strat_complete: 'Complete Revenue Optimization',
      strat_pricing: 'Pricing Strategy',
      strat_commission: 'Commission Optimization',
      strat_upselling: 'Upselling Opportunities',
      strat_retention: 'Customer Retention',
      revenue_optimizer_hero: 'REVENUE OPTIMIZER',
      revenue_optimizer_tagline: 'AI-POWERED FINANCIAL TRAJECTORY ANALYSIS',
      awaiting_ingestion: 'AWAITING PROJECT DATA INGESTION...',
      impact_label: 'IMPACT',
      standard_label: 'STANDARD',
      optimized_label: 'OPTIMIZED',
      critical_label: 'CRITICAL',
      high_load_label: 'HIGH LOAD',
      cat_devops_fintech: 'DevOps / Fintech',
      cat_blockchain_ai: 'Blockchain / AI',
      cat_travel_ai: 'Travel / AI',
      cat_gaming: 'Gaming',
      cat_fintech_ai_biz: 'Fintech / AI / Business',
      cat_innovation: 'Innovation',
      cat_messaging_privacy: 'Messaging / Privacy',
      cat_ai_devops: 'AI / DevOps'
    },
    finstat: {
      live_production: 'B2B SaaS Software | Live on Production',
      company_search: 'Company Search Engine',
      v4_region: 'for the entire V4 region',
      what_selling: 'What are we actually selling?',
      selling_desc: 'Software where companies enter their partner\'s ID and see within 1 second: who really owns them, whether they have hidden debts, and whether they are connected to fraudsters.',
      aggregation: 'We aggregate state registers of Slovakia, Czechia, Poland, and Hungary into one single click.',
      show_how: 'Show how it works',
      what_system_does: 'What exactly does our system do?',
      scrape_registers: '1. Scrapes 4 Registers',
      scrape_desc: 'No more manual searching in ORSR, ARES, or KRS. We download the data automatically into one database.',
      draw_spiders: '2. Draws "Spiders"',
      draw_desc: 'Instead of reading long records, we generate an interactive graph. Instantly see connections to shell companies.',
      erp_conn: '3. ERP Integration',
      erp_desc: 'We connect directly to the client\'s ERP. If a supplier stops paying, our system sends an instant warning.',
      zero_dev_risk: 'Proof of Stability: Zero Dev Risk',
      tech_not_on_paper: 'Technology is not on paper, it is deployed in production.',
      qa_tests: 'Successful QA Tests',
      code_coverage: 'Code coverage 85%+ by tests',
      unfair_advantage: 'Unfair Advantage',
      typo_alg: 'The algorithm connects identities in V4 even with typos.',
      infra: 'Infrastructure',
      scalable_now: 'PostgreSQL, Redis cache. Scalable immediately.',
      erp_gem: 'ERP Integrations: Enterprise Gem',
      erp_deeper: 'Public registers do not contain everything. V4-Finstat goes deeper thanks to connection to accounting.',
      real_time_payments: 'Real-time payment analysis',
      cash_flow_tracking: 'Does the partner pay invoices on time? We monitor cash-flow and liabilities.',
      auto_webhooks: 'Automatic Warnings (Webhooks)',
      risk_score_alert: 'Notification if the risk score of a key supplier deteriorates.',
      ready_connectors: 'Ready Connectors',
      implementation_hours: 'Implementation takes hours. We create enormous "switching costs".',
      business_model: 'Business Model & Profitability',
      high_margin: 'B2B SaaS with high margin and minimal operating costs.',
      pro_plan: 'PRO',
      medium_firms: 'For medium-sized companies',
      biggest_growth: 'Biggest growth',
      logistics: 'For logistics',
      transactional: 'Transactional model',
      banks_insurance: 'For Banks & Insurance',
      op_margin: 'Operating Margin',
      target_arr: 'Target ARR (Year 2)',
      est_churn: 'Estimated Churn',
      legal_compliance: 'Legal & Compliance',
      bulletproof: 'Bulletproof Compliance',
      gdpr_interest: 'GDPR & Legitimate Interest',
      gdpr_desc: 'Data collection is protected by Art. 6(1)(f) of GDPR. We have "Right to erasure" implemented.',
      fair_use: 'Fair Use & Security',
      fair_use_desc: 'Scraping engine uses rotating proxies. We do not overload state servers.',
      disclaimer: 'Automatic Disclaimer',
      disclaimer_desc: 'Each graph cites sources. Exclusion of our legal liability for data.',
      legal_title: '100% Legal & Zero Risk',
      agressive_growth: 'V4-Finstat is designed for aggressive growth but is completely legally untouchable.',
      clean_table: 'We have implemented a complete custom system. With investment, you take a clean table.',
      roadmap: '12-Month Roadmap',
      series_a: 'Series A Dominance',
      investment_ask: 'Investment Requirement',
      potential_10x: 'Potential: 10x within 3 years',
      series_a_val: 'Equity in technology for Series A with valuation of 15M €',
      ready_product: 'Ready Product',
      investment_sales: 'Investment doesn\'t go into development. It goes purely into sales and rapid scaling.',
      scalable_monopoly: 'Scalable Monopoly',
      cross_border_monopoly: 'We create an unshakeable monopoly on cross-border risk analysis.',
      live_demo_btn: 'Proceed to Live Demo',
      enterprise_ready: 'Enterprise Ready',
      q1_title: 'Launch & Traction',
      q1_desc: '0-3 months. First 10 B2B contracts.',
      q2_title: 'V4 Expansion',
      q2_desc: '4-6 months. Market entry in PL and HU.',
      q3_title: 'AI Intelligence',
      q3_desc: '7-9 months. AI risk predictions of the partner.',
      q4_title: 'Series A Dominance',
      q4_desc: '10-12 months. Valuation 15M+ EUR.'
    },
    home: {
      label: 'PROJECTS / REPOSITORY / V5.0',
      heading: 'ENGINEERING \n THE FUTURE \n <span className="text-silver">OF THE WEB.</span>',
      description: 'SYSTEMATIC COLLECTION OF ADVANCED WEB IMPLEMENTATIONS AND AI-DRIVEN ARCHITECTURES, SYNTHESIZED FOR ELITE PERFORMANCE.',
      error_loading: 'Error loading projects',
      error_desc: 'Check your internet connection or API URL.'
    },
    projects_data: {
      v4_finstat_title: 'V4-Finstat',
      v4_finstat_tagline: 'Financial Standardization & Deployment',
      v4_finstat_desc: 'Standardizing Docker environments and namespace for financial data processing.',
      v4_finstat_content: 'This project involved complex Docker orchestration, namespace standardization across microservices, and setting up automated deployment pipelines for VPS and Vercel environments.',
      v4_finstat_architecture: 'Microservices with standardized namespace and containerized deployment pipelines.',
      v4_finstat_market_intel: 'Enterprise compliance automation with high revenue potential in fintech.',
      
      ico_atlas_title: 'ICO Atlas',
      ico_atlas_tagline: 'Crypto Market Intelligence',
      ico_atlas_desc: 'A comprehensive tracking platform for Initial Coin Offerings and market trends.',
      ico_atlas_content: 'Developed a real-time data ingestion engine for tracking ICOs, featuring advanced charting, sentiment analysis, and investor dashboards.',
      ico_atlas_architecture: 'Real-time data ingestion engine with WebSocket updates and sentiment analysis pipeline.',
      ico_atlas_market_intel: 'High-demand market for crypto insights; scalable SaaS model.',
      
      booking_buddy_title: 'Booking Buddy',
      booking_buddy_tagline: 'AI-Powered Travel Assistant',
      booking_buddy_desc: 'Personalized travel planning and booking optimization using AI.',
      booking_buddy_content: 'Built an intelligent travel companion that optimizes booking prices and creates custom itineraries based on user preferences and historical data.',
      booking_buddy_architecture: 'LLM-driven agent architecture for itinerary planning and price optimization.',
      booking_buddy_market_intel: 'Disruptive potential in travel tech; B2C subscription model.',
      
      dream_casino_title: 'The Dream Casino',
      dream_casino_tagline: 'Premium Gaming Experience',
      dream_casino_desc: 'Luxury online casino platform reconstructed with a focus on UX and security.',
      dream_casino_content: 'Redesigned the entire user journey for a premium gambling experience, integrating high-performance gaming engines and robust security protocols.',
      dream_casino_architecture: 'High-concurrency gaming engine with secure payment gateway integration.',
      dream_casino_market_intel: 'High-conversion gaming platform targeting the premium market.',
      
      bizagent_title: 'BizAgent',
      bizagent_tagline: 'AI Business Assistant for Freelancers',
      bizagent_desc: 'Complete solution for invoices, expenses and accounting specifically designed for the Slovak market.',
      bizagent_content: 'BizAgent is an intelligent assistant for small business owners. It offers automatic invoice numbering, PAY by square QR codes, OCR receipt scanning, and AI-driven expense categorization.',
      bizagent_architecture: 'Micro-services on Firebase with Riverpod state management and Offline-first PWA sync.',
      bizagent_market_intel: 'Targeted at 600k+ SZČO in Slovakia with potential for automated accounting.',
      
      lumina_os_title: 'Lumina OS',
      lumina_os_tagline: 'Next-Gen Operating System',
      lumina_os_desc: 'A concept OS focusing on neural interfaces and adaptive UI design.',
      lumina_os_content: 'Design and architectural exploration of an operating system that learns user habits to proactively surface relevant tools and information.',
      lumina_os_architecture: 'Neural-first kernel design with adaptive UI generation based on brain-computer interface concept.',
      lumina_os_market_intel: 'Edge-case innovation with long-term R&D value.',
      
      betauthority_title: 'BetAuthority',
      betauthority_tagline: 'European Casino Rankings',
      betauthority_desc: 'Comparison tool for online casinos and betting platforms with real-time data and fair terms.',
      betauthority_content: 'BetAuthority is an advanced data-driven comparison tool for online casinos. The system analyzes over 127 operators and provides real-time trust scoring.',
      betauthority_architecture: 'Automated data scraping and verification network for real-time betting audits.',
      betauthority_market_intel: 'Market leader in affiliate transparency and data-driven trust scoring.',
      
      neon_bloom_messenger_title: 'Neon Bloom Messenger',
      neon_bloom_messenger_tagline: 'Premium Communication Ecosystem',
      neon_bloom_messenger_desc: 'High-performance, privacy-focused communication platform built on Matrix protocol.',
      neon_bloom_messenger_content: 'Complete communication infrastructure designed for privacy, speed, and premium aesthetics. Built on Matrix protocol with Bun and React.',
      neon_bloom_messenger_architecture: 'Decentralized messaging infrastructure with E2E encryption and ultra-fast Bun-powered API.',
      neon_bloom_messenger_market_intel: 'Privacy-first communication niche with high growth potential.',
      
      v4_finstat_v5_0_title: 'V4-Finstat v5.0',
      v4_finstat_v5_0_tagline: 'Enterprise Ready B2B SaaS',
      v4_finstat_v5_0_desc: 'SaaS software for B2B monitoring of companies in the V4 region.',
      v4_finstat_v5_0_content: 'V4-Finstat v5.0 is an enterprise solution for B2B company monitoring. It integrates state registers of SR, CZ, PL and HU with interactive graphs.',
      v4_finstat_v5_0_architecture: 'Enterprise-grade B2B SaaS architecture with centralized data aggregation from V4 regional registries.',
      v4_finstat_v5_0_market_intel: 'High-margin B2B SaaS, strong recurring revenue potential, low churn rate.',
      
      rubberduck_space_title: 'RubberDuck.Space',
      rubberduck_space_tagline: 'AI-Powered Autonomous Code Analysis & Repair',
      rubberduck_space_desc: 'Autonomous code analysis and repair platform for modern engineering teams.',
      rubberduck_space_content: 'RubberDuck.Space is an AI-powered platform providing autonomous code analysis and repair. Our agent understands the root cause of issues before proposing fixes.',
      rubberduck_space_architecture: 'Autonomous agentic architecture with recursive code analysis and surgical patching loops.',
      rubberduck_space_market_intel: 'Enterprise-grade AI code repair targeting 40%+ reduction in technical debt maintenance.',
      rubberduck_space_arch_analysis: 'Multi-agent orchestration layer with isolated sandbox verification and cryptographic audit trails.',
      rubberduck_space_security_audit: 'Hardened local data processing with zero-training data policy and full provenance tracking.',
      rubberduck_space_budget: '$50k - $120k',
      rubberduck_space_timeline: '4-6 Months',
      
      v4_finstat_arch_analysis: 'Precision-engineered Docker orchestration layer with isolated network namespaces.',
      v4_finstat_security_audit: 'Hardened container images with automated vulnerability scanning in CI.',
      v4_finstat_budget: '$15k - $30k',
      v4_finstat_timeline: '2-3 Months',
      
      ico_atlas_arch_analysis: 'High-concurrency data stream processing with distributed Postgres scaling.',
      ico_atlas_security_audit: 'Secure WebSocket protocols with JWT-based tiered access controls.',
      ico_atlas_budget: '$40k - $75k',
      ico_atlas_timeline: '4-6 Months',
      
      booking_buddy_arch_analysis: 'Self-correcting agent chains with recursive prompt optimization techniques.',
      booking_buddy_security_audit: 'Anonymized PII data handling with strict API rate limiting protocols.',
      booking_buddy_budget: '$25k - $50k',
      booking_buddy_timeline: '3-4 Months',
      
      dream_casino_arch_analysis: 'Low-latency event-driven architecture with sub-10ms state synchronization.',
      dream_casino_security_audit: 'Multi-signature payment escrow with distributed anti-fraud monitoring.',
      dream_casino_budget: '$60k - $120k',
      dream_casino_timeline: '5-8 Months',
      
      bizagent_arch_analysis: 'High-performance CanvasKit renderer with robust OCR data extraction pipeline.',
      bizagent_security_audit: 'Hardened security rules with validated file uploads and encrypted PII.',
      bizagent_budget: '$30k - $70k',
      bizagent_timeline: '4-6 Months',
      
      lumina_os_arch_analysis: 'Zero-overhead Rust-based kernel targeting WebAssembly sandboxed runtimes.',
      lumina_os_security_audit: 'Memory-safe execution environment with cryptographic isolation layers.',
      lumina_os_budget: '$200k+',
      lumina_os_timeline: '12-24 Months',
      
      betauthority_arch_analysis: 'Distributed scraping cluster with AI-based pattern recognition for audit detection bypass.',
      betauthority_security_audit: 'Encrypted database layers with anonymized transaction ledger.',
      betauthority_budget: '$45k - $80k',
      betauthority_timeline: '4-6 Months',
      
      neon_bloom_messenger_arch_analysis: 'Zero-knowledge server architecture with distributed data shards via MinIO.',
      neon_bloom_messenger_security_audit: 'Full Matrix E2EE implementation with automated session termination and secure credential vault.',
      neon_bloom_messenger_budget: '$50k - $90k',
      neon_bloom_messenger_timeline: '4-7 Months',
      
      v4_finstat_v5_0_arch_analysis: 'Highly scalable monitoring system with real-time risk alerts and ERP-integrated fraud detection.',
      v4_finstat_v5_0_security_audit: 'GDPR-compliant with automated audit logging and hardened data isolation.',
      v4_finstat_v5_0_budget: '$50k - $100k',
      v4_finstat_v5_0_timeline: '3-6 Months'
    },
    ingestion: {
      tech_stack: 'Tech Stack',
      architecture: 'Architecture',
      market_intel: 'Market Intel',
      upload_zip: 'Upload ZIP (AI Analysis)',
      processing: 'Processing ZIP...',
      analyzing: 'AI Analyzing Codebase...',
      success: 'Project Successfully Ingested',
      refine: 'Refine Details',
      save: 'Save to Repository'
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('SK');

  useEffect(() => {
    const saved = localStorage.getItem('larsen_lang') as Language;
    if (saved) setLanguage(saved);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('larsen_lang', lang);
  };

  const t = (key: string, section: string = 'common'): string => {
    try {
      return (translations[language] as any)[section][key] || key;
    } catch {
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
