'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'SK' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

const translations = {
  SK: {
    common: {
      projects: 'PROJEKTY',
      content_ai: 'CONTENT AI',
      about: 'O NÁS',
      contact: 'KONTAKT',
      scale: 'SCALE_RESOURCES',
      production: 'PRODUKCIA',
      stable: 'STABILNÁ',
    },
    seo: {
      title: 'LARSEN EVANS PROJECTS',
      description: 'Elitná prehliadka prémiových PWA a AI riešení od LARSEN EVANS',
    },
    tickers: {
      connected: 'LARSEN_EVANS_CORE_PRIPOJENÝ',
      active: 'SYNAPSE_STREAM_v4.5_AKTÍVNY',
      analysis: 'ELITNÁ_ANALÝZA_SEKTORA',
      data_lock: 'PROPRIETÁRNY_DÁTOVÝ_ZÁMOK',
      filter: 'NEURÁLNY_FILTER_LE_v1.0'
    },
    repository: {
      categories: 'KATEGÓRIE / FILTER',
      all: 'VŠETKO',
      syncing: 'SYNCHRONIZÁCIA DÁT...',
      results: 'VÝSLEDKY / INDEX v5.2',
      sector_total: 'CELKOVO V SEKTORE',
      no_results: 'Nenašli sa žiadne dátové sekvencie',
      no_results_desc: 'AKTUÁLNY FILTRAČNÝ KOEFICIENT "{category}" VRACIA PRÁZDNE VYFRUOVACIE VYMEDZENIA. UPRAVTE PARAMETRE PRE SYNCHRONIZÁCIU.',
      reset: 'RESETOVAŤ PARAMETRE',
      live_feed: 'LIVE_FEED / v5.2',
      buffer: 'BUFFER',
      engine: 'ENGINE',
      seq_year: 'SEKVENCIA / ROK',
      contract_client: 'KONTRAKT / KLIENT'
    },
    enterprise: {
      tagline: 'LARSEN ENTERPRISE v5.0',
      proprietary: 'AKTÍVNA PROPRIETÁRNA ARCHITEKTÚRA',
      heading: 'ŠKÁLUJTE \n ZA HRANICE.',
      description: 'Inteligentné podnikové riešenia a AI-driven infraštruktúra talentov pre organizácie s vysokou dynamikou.',
      strategy_title: 'AI STRATÉGIA',
      strategy_desc: 'End-to-end stratégie automatizácie využívajúce architektúru LARSEN-SYNTH.',
      elite_title: 'ELITNÝ VÝBER',
      elite_desc: 'AI-preverený pool talentov optimalizovaný pre nasadenie v podnikovom meradle.',
      secure_title: 'ZABEZPEČENÁ INFRA',
      secure_desc: 'Bezpečnostné protokoly vojenskej úrovne pre všetky AI integrované pracovné postupy.',
      global_title: 'GLOBÁLNY DOSAH',
      global_desc: 'Distribuované systémy navrhnuté pre škálovateľnosť vo viacerých regiónoch.',
      learn_more: 'Zistiť viac',
      new_feature: 'NOVÁ FUNKCIA',
      proposal_heading: 'AI PROPOSAL \n ENGINE.',
      proposal_desc: 'Generujte komplexné obchodné návrhy a architektonické plány za 30 sekúd.',
      access_alpha: 'Prístup k Alfe',
      market_intel: 'TRHOVÁ INTELIGENCIA',
      why_scale: 'PREČO ŠKÁLOVAŤ?',
      uptime: 'GARANTOVANÝ 99.9% UPTIME',
      architects: 'DEDIKOVANÍ ARCHITEKTI',
      realtime: 'VÝKON V REÁLNOM ČASE'
    },
    generator: {
      tagline: 'LARSEN EVANS SYNTHESIS v5.2',
      heading: 'CONTENT \n GENERATOR.',
      description: 'Elitný marketingový výstup pre globálne projekty, syntetizovaný proprietárnou architektúrou LARSEN s integráciou Gemini 1.5 Pro.',
      type_label: '01 / TYP OBSAHU',
      core_data: '02 / ZÁKLADNÉ DÁTA',
      project_title: 'Názov projektu',
      keywords: 'Cieľové kľúčové slová',
      placeholder_title: 'napr. BRUTALISTICKÁ VILA',
      placeholder_keywords: 'napr. BETÓN, MINIMALIZMUS, SKLO',
      synth_button: 'SYNTETIZOVAŤ...',
      generate_button: 'GENEROVAŤ DÁTA',
      footer_note: 'Využíva architektúru Gemini 1.5 Pro pre precíznu syntézu obsahu, sémantické mapovanie a štrukturálnu verifikáciu.',
      output_label: 'VÝSTUP / BUFFER / v5.2 / SYNC: AKTÍVNY',
      clone_data: 'KLONOVAŤ DÁTA',
      copied: 'SKOPÍROVANÉ DO BUFFRU',
      awaiting: 'Čakanie na vstupnú sekvenciu',
      ready: 'Systém pripravený na syntézu dát',
      error_title: 'Chyba pri generovaní obsahu',
      error_desc: 'Skontrolujte API kľúč alebo skúste znova neskôr.',
      blog: 'Blogový článok',
      case_study: 'Case Study',
      social: 'Sociálne siete',
      marketing: 'Marketingový text',
      blog_prompt: 'Napíš pútavý blogový článok o projekte',
      case_study_prompt: 'Vytvor detailnú prípadovú štúdiu pre projekt',
      social_prompt: 'Vygeneruj príspevky na Instagram, LinkedIn a Facebook pre',
      marketing_prompt: 'Vytvor predajný text pre webovú stránku o',
      prompt_suffix: 'Formátuj v Markdown. Použi štruktúrované nadpisy a zoznamy.',
      keywords_label: 'Kľúčové slová:'
    },
    detail: {
      return: 'INDEX / SPÄŤ',
      system_stable: 'SYSTÉM_STABILNÝ',
      overview: 'ANALÝZA / PREHĽAD',
      deploy: 'SPUSTIŤ DEPLOY',
      enhance_vision: 'ROZŠÍRENÝ REŽIM VIDENIA',
      intel: 'PROJEKTOVÝ INTEL',
      ident_client: 'KLIENT / ENTITA',
      sector_cat: 'SEKTOR / KATEGÓRIA',
      mech_type: 'MECHANIZMUS / TYP',
      tx_timestamp: 'TIMESTAMP / ROK',
      encryption: 'ENKRYPCIA DÁT',
      verification_note: 'Všetky projektové dáta sú overené AI protokolom Larsen Evans.',
      neural_intel: 'NEURÁLNA INTELIGENCIA',
      stack_intelligence: 'STACK INTELLIGENCE',
      arch_neural_map: 'ARCHITEKTÚRA / MAPA',
      market_potential: 'TRHOVÝ POTENCIÁL',
      view_presentation: 'SPUSTIŤ PREZENTÁCIU',
      not_found: 'Projekt nebol nájdený',
      back_to_list: 'Späť na zoznam projektov',
      arch_analysis: 'ARCHITEKTURALNA ANALÝZA',
      security_audit: 'BEZPEČNOSTNÝ AUDIT',
      sync_protocol: 'SYNCHRONIZAČNÝ PROTOKOL'
    },
    ai_tools: {
      search_assistant: 'ASISTENT VYHĽADÁVANIA',
      neural_engine: 'SÉMANTICKÝ NEURÁLNY ENGINE :: STATUS_AKTÍVNY',
      query_placeholder: 'MOLEKULÁRNY VSTUP DOPYTU / ZADAJTE PARAMETRE...',
      execute: 'VYKONAŤ',
      syncing: 'SYNCHRONIZÁCIA',
      neural_suggestions: 'NEURÁLNE NÁVRHY',
      logic_overrides: 'LOGICKÉ PREPÍSANIA',
      market_analyzer: 'SYSTÉMOVÁ ANALÝZA',
      market_intel: 'TRHOVÁ INTELIGENCIA / CORE V4.0',
      sector_selection: 'VÝBER CORE SEKTORA',
      insight_data: 'ÚDAJE O VHĽADE',
      volume_demand: 'OBJEM / DOPYT',
      valuation_price: 'OCEŇOVANIE / CENA',
      strategic_vectors: 'STRATEGICKÉ VEKTORY',
      alpha_ops: 'ALPHA OPERÁCIE',
      reevaluate: 'PREHODNOTIŤ TRH',
      export_raw: 'EXPORTOVAŤ RAW DÁTA',
      system_standby: 'SYSTÉM V POHOTOVOSTI',
      revenue_optimizer: 'OPTIMALIZÁCIA VÝNOSOV',
      revenue_desc: 'AI-poháňaná analýza na maximalizáciu výnosového potenciálu vašej platformy',
      optimization_strategy: 'STRATÉGIA OPTIMALIZÁCIE',
      optimizing_msg: 'Optimalizácia výnosovej stratégie...',
      revenue_overview: 'PREHĽAD VÝNOSOV',
      current_revenue: 'AKTUÁLNY VÝNOS',
      potential_revenue: 'POTENCIÁLNY VÝNOS',
      revenue_increase: 'NÁRAST VÝNOSOV',
      optimization_areas: 'OBLASTI OPTIMALIZÁCIE',
      top_recommendations: 'TOP ODPORÚČANIA',
      implementation_steps: 'KROKY IMPLEMENTÁCIE',
      re_optimize: 'PRE-OPTIMALIZOVAŤ',
      export_plan: 'EXPORTOVAŤ PLÁN',
      ai_assistant: 'AI_ASISTENT / v5.2',
      revenue_optimizer_title: 'OPTIMALIZÁTOR VÝNOSOV',
      active_analysis: 'AKTÍVNA_ANALÝZA',
      mapping_msg: 'Syntetickí agenti momentálne mapujú trhové premenné a výnosové toky pre túto konkrétnu architektonickú sekvenciu.',
      core_sync_ready: 'CORE_SYNCHRONIZÁCIA_PRIPRAVENÁ',
      query_assistant: 'ASISTENT DOPYTU',
      suggestions_prompt: 'Generuj 5 krátkych profesionálnych návrhov na vyhľadávanie pre platformu trhoviska projektov. Príklady: "Moderná PWA", "Next.js API", "AI Dashboard". Vráť ako JSON pole reťazcov.',
      enhance_prompt: 'Vylepši tento dopyt na vyhľadávanie pre vysoko presné párovanie projektov: "{searchQuery}". Kontext: {context}. Vráť iba vylepšený dopyt.',
      analyzer_prompt: 'Analyzuj aktuálne trendy na trhu pre {category} projekty. Zameraj sa na: 1. Vzorce dopytu a oblasti rastu, 2. Cenové trendy a očakávania rozpočtu, 3. Najžiadanejšie zručnosti a technológie, 4. Vzorce časovej osi projektov, 5. Regionálne rozdiely na trhu, 6. Vznikajúce príležitosti. Poskytni realizovateľné poznatky pre platformu trhoviska projektov. Vráť štruktúrované dáta so špecifickými odporúčaniami.',
      fallback_demand: 'Vysoký dopyt po vývoji webových aplikácií a AI projektoch',
      fallback_pricing: 'Priemerný rozpočet projektu: 5000 - 15000 €',
      fallback_rec1: 'Zamerajte sa na AI a projekty strojového učenia',
      fallback_rec2: 'Cielte na projekty so stredným rozpočtom (5k - 15k €)',
      fallback_rec3: 'Zvýraznite projekty s jasnými časovými osami',
      fallback_rec4: 'Zdôraznite služby zabezpečenia kvality (QA)',
      fallback_opp1: 'Riešenia pre prácu na diaľku',
      fallback_opp2: 'Optimalizácia e-commerce',
      fallback_opp3: 'Vývoj mobilných aplikácií',
      fallback_opp4: 'Služby migrácie do cloudu',
      cat_all: 'všetko',
      cat_web: 'vývoj webu',
      cat_mobile: 'mobilné aplikácie',
      cat_ai: 'ai a ml',
      cat_ecommerce: 'e-commerce',
      cat_automation: 'automatizácia biznisu'
    },
    finstat: {
      live_production: 'B2B SaaS Softvér | Live na produkcii',
      company_search: 'Vyhľadávač firiem',
      v4_region: 'pre celý región V4',
      what_selling: 'Čo vlastne predávame?',
      selling_desc: 'Softvér, do ktorého firmy zadajú IČO svojho partnera a do 1 sekundy vidia: kto ho reálne vlastní, či nemá skryté dlhy a či nie je prepojený na podvodníkov.',
      aggregation: 'Agregujeme štátne registre Slovenska, Česka, Poľska a Maďarska do jedného kliknutia.',
      show_how: 'Ukázať ako to funguje',
      what_system_does: 'Čo presne náš systém robí?',
      scrape_registers: '1. Vykráda 4 Registre',
      scrape_desc: 'Už žiadne ručné hľadanie v ORSR, ARESe, či KRS. My tie dáta sťahujeme automaticky do jednej databázy.',
      draw_spiders: '2. Kreslí "Pavúkov"',
      draw_desc: 'Namiesto čítania výpisov vygenerujeme interaktívny graf. Okamžite vidíte prepojenie na schránkové firmy.',
      erp_conn: '3. Napojenie na ERP',
      erp_desc: 'Napojíme sa na ERP klienta. Ak dodávateľ prestane platiť, náš systém pošle okamžité varovanie.',
      zero_dev_risk: 'Proof of Stability: Nulové Dev Riziko',
      tech_not_on_paper: 'Technológia nie je na papieri, je nasadená v produkcii.',
      qa_tests: 'Úspešných QA Testov',
      code_coverage: 'Pokrytie kódu 85%+ testami',
      unfair_advantage: 'Unfair Advantage',
      typo_alg: 'Algoritmus spája identity vo V4 aj pri preklepoch.',
      infra: 'Infraštruktúra',
      scalable_now: 'PostgreSQL, Redis cache. Škálovateľné ihneď.',
      erp_gem: 'ERP Integrácie: Enterprise Klenot',
      erp_deeper: 'Verejné registre neobsahujú všetko. V4-Finstat ide hlbšie vďaka napojeniu na účtovníctvo.',
      real_time_payments: 'Analýza platieb v reálnom čase',
      cash_flow_tracking: 'Platí partner faktúry včas? Sledujeme cash-flow a záväzky.',
      auto_webhooks: 'Automatické varovania (Webhooks)',
      risk_score_alert: 'Notifikácia, ak sa zhorší risk score kľúčového dodávateľa.',
      ready_connectors: 'Pripravené konektory',
      implementation_hours: 'Implementácia trvá hodiny. Vytvárame enormné "switching costs".',
      business_model: 'Biznis Model & Ziskovosť',
      high_margin: 'B2B SaaS s vysokou maržou a minimálnymi nákladmi.',
      pro_plan: 'PRO',
      medium_firms: 'Pre stredné firmy',
      biggest_growth: 'Najväčší rast',
      logistics: 'Pre logistiku',
      transactional: 'Transakčný model',
      banks_insurance: 'Pre Banky & Poisťovne',
      op_margin: 'Prevádzková Marža',
      target_arr: 'Cieľové ARR (Rok 2)',
      est_churn: 'Odhadovaný Churn',
      legal_compliance: 'Legal & Compliance',
      bulletproof: 'Bulletproof Compliance',
      gdpr_interest: 'GDPR & Oprávnený záujem',
      gdpr_desc: 'Zber dát je chránený čl. 6(1)(f) GDPR. Máme implementované "Právo na výmaz".',
      fair_use: 'Fair Use & Bezpečnosť',
      fair_use_desc: 'Scraping engine využíva rotujúce proxy. Nepreťažujeme štátne servery.',
      disclaimer: 'Automatický Disclaimer',
      disclaimer_desc: 'Každý graf cituje zdroje. Vylúčenie našej právnej zodpovednosti za dáta.',
      legal_title: '100% Legal & Zero Risk',
      agressive_growth: 'V4-Finstat je navrhnutý tak, aby agresívne rástol, no právne bol nedotknuteľný.',
      clean_table: 'Implementovali sme kompletný systém na mieru. Pri investícii preberáte čistý stôl.',
      roadmap: '12-Mesačná Roadmapa',
      series_a: 'Series A Dominance',
      investment_ask: 'Investičná požiadavka',
      potential_10x: 'Potenciál: 10x do 3 rokov',
      series_a_val: 'Podiel v technológii pre Series A s valuáciou 15M €',
      ready_product: 'Hotový Produkt',
      investment_sales: 'Investícia nejde do vývoja. Ide čisto do predaja a rýchleho znásobenia tržieb.',
      scalable_monopoly: 'Škálovateľný Monopol',
      cross_border_monopoly: 'Vytvárame neohrozený monopol na cezhraničnú risk analýzu.',
      live_demo_btn: 'Prejsť k Live Demonštrácii',
      enterprise_ready: 'Enterprise Ready',
      q1_title: 'Launch & Traction',
      q1_desc: '0-3 mes. Prvých 10 B2B kontraktov.',
      q2_title: 'V4 Expansion',
      q2_desc: '4-6 mes. Vstup na trh PL a HU.',
      q3_title: 'AI Intelligence',
      q3_desc: '7-9 mes. AI predikcie rizík partnera.',
      q4_title: 'Series A Dominance',
      q4_desc: '10-12 mes. Valuácia 15M+ EUR.'
    },
    home: {
      label: 'PROJEKTY / REPOZITÁR / V5.0',
      heading: 'INŽINIERING \n BUDÚCNOSTI \n <span className="text-silver">WEBU.</span>',
      description: 'SYSTEMATICKÁ ZBIERKA POKROČILÝCH WEBOVÝCH IMPLEMENTÁCIÍ A AI ARCHITEKTÚR, SYNTETIZOVANÁ PRE ELITNÝ VÝKON.',
      error_loading: 'Chyba pri načítaní projektov',
      error_desc: 'Skontrolujte pripojenie k internetu alebo API URL.'
    },
    projects_data: {
      v4_finstat_title: 'V4-Finstat',
      v4_finstat_tagline: 'Finančná Štardardizácia a Nasadenie',
      v4_finstat_desc: 'Štandardizácia Docker prostredí a menných priestorov pre spracovanie finančných dát.',
      ico_atlas_title: 'ICO Atlas',
      ico_atlas_tagline: 'Kryptomenová Trhová Inteligencia',
      ico_atlas_desc: 'Komplexná sledovacia platforma pre počiatočné ponuky mincí a trhové trendy.',
      booking_buddy_title: 'Booking Buddy',
      booking_buddy_tagline: 'AI Cestovný Asistent',
      booking_buddy_desc: 'Personalizované plánovanie ciest a optimalizácia rezervácií pomocou AI.',
      dream_casino_title: 'The Dream Casino',
      dream_casino_tagline: 'Prémiový Herný Zážitok',
      dream_casino_desc: 'Luxusná online kasíno platforma zrekonštruovaná s dôrazom na UX a bezpečnosť.',
      bizagent_title: 'BizAgent',
      bizagent_tagline: 'AI Business Assistant pre SZČO',
      bizagent_desc: 'Kompletné riešenie pre faktúry, výdavky a accounting špeciálne navrhnuté pre slovenský trh.',
      lumina_os_title: 'Lumina OS',
      lumina_os_tagline: 'Operačný Systém Novej Generácie',
      lumina_os_desc: 'Konceptualizácia OS zameraná na neurálne rozhrania a adaptívny dizajn UI.',
      betauthority_title: 'BetAuthority',
      betauthority_tagline: 'Hodnotenie kasín v celej Európe',
      betauthority_desc: 'Porovnávací nástroj pre online kasína a stávkové platformy s dátami v reálnom čase, výplatami a férovými podmienkami.',
      neon_bloom_messenger_title: 'Neon Bloom Messenger',
      neon_bloom_messenger_tagline: 'Prémiový komunikačný ekosystém',
      neon_bloom_messenger_desc: 'Vysokovýkonná platforma zameraná na súkromie postavená na protokole Matrix.',
      v4_finstat_v5_0_title: 'V4-Finstat v5.0',
      v4_finstat_v5_0_tagline: 'Enterprise Ready B2B SaaS',
      v4_finstat_v5_0_desc: 'SaaS softvér pre B2B monitoring firiem v regióne V4.',
      rubberduck_space_title: 'RubberDuck.Space',
      rubberduck_space_tagline: 'AI-Powered Autonomous Code Analysis & Repair',
      rubberduck_space_desc: 'Platforma na autonómnu analýzu a opravu kódu pre moderné inžinierske tímy.'
    },
    ingestion: {
      tech_stack: 'Technologický Stack',
      architecture: 'Architektúra',
      market_intel: 'Market Intel',
      upload_zip: 'Nahrať ZIP (AI Analýza)',
      processing: 'Spracovávam ZIP...',
      analyzing: 'AI Analyzuje kódovú bázu...',
      success: 'Projekt úspešne načítaný',
      refine: 'Upraviť detaily',
      save: 'Uložiť do repozitára'
    }
  },
  EN: {
    common: {
      projects: 'PROJECTS',
      content_ai: 'CONTENT AI',
      about: 'ABOUT US',
      contact: 'CONTACT',
      scale: 'SCALE_RESOURCES',
      production: 'PRODUCTION',
      stable: 'STABLE',
    },
    seo: {
      title: 'LARSEN EVANS PROJECTS',
      description: 'Elite Showcase of Premium PWA and AI Solutions by LARSEN EVANS',
    },
    tickers: {
      connected: 'LARSEN_EVANS_CORE_CONNECTED',
      active: 'SYNAPSE_STREAM_v4.5_ACTIVE',
      analysis: 'ELITE_SECTOR_ANALYSIS',
      data_lock: 'PROPRIETARY_DATA_LOCK',
      filter: 'NEURAL_FILTER_LE_v1.0'
    },
    repository: {
      categories: 'CATEGORIES / FILTER',
      all: 'ALL',
      syncing: 'SYNCING DATA...',
      results: 'RESULTS / INDEX v5.2',
      sector_total: 'SECTOR TOTAL',
      no_results: 'No Data Sequences Found',
      no_results_desc: 'THE CURRENT FILTER COEFFICIENT "{category}" IS RETURNING EMPTY BUFFER STREAMS. ADJUST PARAMETERS FOR SYNCHRONIZATION.',
      reset: 'RESET BUFFER PARAMETERS',
      live_feed: 'LIVE_FEED / v5.2',
      buffer: 'BUFFER',
      engine: 'ENGINE',
      seq_year: 'SEQUENCE / YEAR',
      contract_client: 'CONTRACT / CLIENT'
    },
    enterprise: {
      tagline: 'LARSEN ENTERPRISE v5.0',
      proprietary: 'PROPRIETARY ARCHITECTURE ACTIVE',
      heading: 'SCALE \n BEYOND.',
      description: 'Intelligent enterprise solutions and AI-driven talent infrastructure for high-velocity organizations.',
      strategy_title: 'AI STRATEGY',
      strategy_desc: 'End-to-end automation strategies using LARSEN-SYNTH architecture.',
      elite_title: 'ELITE SELECTION',
      elite_desc: 'AI-vetted talent pool optimized for enterprise-scale deployments.',
      secure_title: 'SECURE INFRA',
      secure_desc: 'Military-grade security protocols for all AI-integrated workflows.',
      global_title: 'GLOBAL REACH',
      global_desc: 'Distributed systems designed for multi-region scalability.',
      learn_more: 'Learn More',
      new_feature: 'NEW FEATURE',
      proposal_heading: 'AI PROPOSAL \n ENGINE.',
      proposal_desc: 'Generate comprehensive business proposals and architecture blueprints in 30 seconds.',
      access_alpha: 'Access Alpha',
      market_intel: 'MARKET INTELLIGENCE',
      why_scale: 'WHY SCALE?',
      uptime: 'GUARANTEED 99.9% UPTIME',
      architects: 'DEDICATED ARCHITECTS',
      realtime: 'REAL-TIME PERFORMANCE'
    },
    generator: {
      tagline: 'LARSEN EVANS SYNTHESIS v5.2',
      heading: 'CONTENT \n GENERATOR.',
      description: 'Elite marketing output for global projects, synthesized by proprietary LARSEN architecture with Gemini 1.5 Pro integration.',
      type_label: '01 / CONTENT TYPE',
      core_data: '02 / CORE DATA',
      project_title: 'Project Title',
      keywords: 'Target Keywords',
      placeholder_title: 'e.g., BRUTALIST VILLA',
      placeholder_keywords: 'e.g., CONCRETE, MINIMAL, GLASS',
      synth_button: 'SYNTHESIZING...',
      generate_button: 'GENERATE DATA',
      footer_note: 'Utilizing Gemini 1.5 Pro architecture for high-fidelity content synthesis, semantic mapping, and structural verification.',
      output_label: 'OUTPUT / BUFFER / v5.2 / SYNC: ACTIVE',
      clone_data: 'CLONE DATA',
      copied: 'COPIED TO BUFFER',
      awaiting: 'Awaiting Input Sequence',
      ready: 'System ready for data synthesis',
      error_title: 'Content Generation Error',
      error_desc: 'Check API key or try again later.',
      blog: 'Blog Post',
      case_study: 'Case Study',
      social: 'Social Networks',
      marketing: 'Marketing Text',
      blog_prompt: 'Write an engaging blog post about the project',
      case_study_prompt: 'Create a detailed case study for the project',
      social_prompt: 'Generate Instagram, LinkedIn, and Facebook posts for',
      marketing_prompt: 'Create a selling text for a website about',
      prompt_suffix: 'Format in Markdown. Use structured headings and lists.',
      keywords_label: 'Keywords:'
    },
    detail: {
      return: 'INDEX / RETURN',
      system_stable: 'SYSTEM_STABLE',
      overview: 'ANALYSIS / OVERVIEW',
      deploy: 'EXECUTE DEPLOY',
      enhance_vision: 'ENHANCED VISION MODE',
      intel: 'PROJECT INTEL',
      ident_client: 'CLIENT / ENTITY',
      sector_cat: 'SECTOR / CATEGORY',
      mech_type: 'MECHANISM / TYPE',
      tx_timestamp: 'TIMESTAMP / YEAR',
      encryption: 'DATA ENCRYPTION',
      verification_note: 'All project data is verified by Larsen Evans AI protocol.',
      neural_intel: 'NEURAL INTELLIGENCE',
      stack_intelligence: 'STACK INTELLIGENCE',
      arch_neural_map: 'ARCH_NEURAL_MAP',
      market_potential: 'MARKET POTENTIAL',
      view_presentation: 'VIEW PRESENTATION',
      not_found: 'Project Not Found',
      back_to_list: 'Back to projects index',
      arch_analysis: 'ARCHITECTURAL ANALYSIS',
      security_audit: 'SECURITY AUDIT',
      sync_protocol: 'SYNC PROTOCOL'
    },
    ai_tools: {
      search_assistant: 'SEARCH ASSISTANT',
      neural_engine: 'SEMANTIC NEURAL ENGINE :: STATUS_ACTIVE',
      query_placeholder: 'MOLECULAR QUERY INPUT / ENTER PARAMETERS...',
      execute: 'EXECUTE',
      syncing: 'SYNCING',
      neural_suggestions: 'NEURAL SUGGESTIONS',
      logic_overrides: 'LOGIC OVERRIDES',
      market_analyzer: 'SYSTEM ANALYSIS',
      market_intel: 'MARKET INTELLIGENCE / CORE V4.0',
      sector_selection: 'CORE SECTOR SELECTION',
      insight_data: 'INSIGHT DATA',
      volume_demand: 'VOLUME / DEMAND',
      valuation_price: 'VALUATION / PRICE',
      strategic_vectors: 'STRATEGIC VECTORS',
      alpha_ops: 'ALPHA OPS',
      reevaluate: 'REEVALUATE MARKET',
      export_raw: 'EXPORT RAW DATA',
      system_standby: 'SYSTEM STANDBY',
      revenue_optimizer: 'REVENUE OPTIMIZATION',
      revenue_desc: 'AI-powered analysis to maximize your platform\'s revenue potential',
      optimization_strategy: 'OPTIMIZATION STRATEGY',
      optimizing_msg: 'Optimizing revenue strategy...',
      revenue_overview: 'REVENUE OVERVIEW',
      current_revenue: 'CURRENT REVENUE',
      potential_revenue: 'POTENTIAL REVENUE',
      revenue_increase: 'REVENUE INCREASE',
      optimization_areas: 'OPTIMIZATION AREAS',
      top_recommendations: 'TOP RECOMMENDATIONS',
      implementation_steps: 'IMPLEMENTATION STEPS',
      re_optimize: 'RE-OPTIMIZE',
      export_plan: 'EXPORT PLAN',
      ai_assistant: 'AI_ASSISTANT / v5.2',
      revenue_optimizer_title: 'REVENUE_OPTIMIZER',
      active_analysis: 'ACTIVE_ANALYSIS',
      mapping_msg: 'Synthetic agents are currently mapping market variables and revenue streams for this specific architectural sequence.',
      core_sync_ready: 'CORE_SYNC_READY',
      query_assistant: 'QUERY ASSISTANT',
      suggestions_prompt: 'Generate 5 short professional search suggestions for a project marketplace platform. Examples: "Modern PWA", "Next.js API", "AI Dashboard". Return as a JSON array of strings.',
      enhance_prompt: 'Enhance this search query for high-fidelity project matching: "{searchQuery}". Context: {context}. Return enhanced query only.',
      analyzer_prompt: 'Analyze the current market trends for {category} projects. Focus on: 1. Demand patterns and growth areas, 2. Pricing trends and budget expectations, 3. Most in-demand skills and technologies, 4. Project timeline patterns, 5. Regional market differences, 6. Emerging opportunities. Provide actionable insights for a project marketplace platform. Return structured data with specific recommendations.',
      fallback_demand: 'High demand in web development and AI projects',
      fallback_pricing: 'Average project budget: $5000-15000',
      fallback_rec1: 'Focus on AI and machine learning projects',
      fallback_rec2: 'Target mid-range budget projects ($5k-15k)',
      fallback_rec3: 'Highlight projects with clear timelines',
      fallback_rec4: 'Emphasize quality assurance services',
      fallback_opp1: 'Remote work solutions',
      fallback_opp2: 'E-commerce optimization',
      fallback_opp3: 'Mobile app development',
      fallback_opp4: 'Cloud migration services',
      cat_all: 'all',
      cat_web: 'web development',
      cat_mobile: 'mobile apps',
      cat_ai: 'ai and ml',
      cat_ecommerce: 'e-commerce',
      cat_automation: 'business automation'
    },
    finstat: {
      live_production: 'B2B SaaS Software | Live on Production',
      company_search: 'Company Search Engine',
      v4_region: 'for the entire V4 region',
      what_selling: 'What are we actually selling?',
      selling_desc: 'Software where companies enter their partner\'s ID and see within 1 second: who really owns them, whether they have hidden debts, and whether they are connected to fraudsters.',
      aggregation: 'We aggregate state registers of Slovakia, Czechia, Poland, and Hungary into one single click.',
      show_how: 'Show how it works',
      what_system_does: 'What exactly does our system do?',
      scrape_registers: '1. Scrapes 4 Registers',
      scrape_desc: 'No more manual searching in ORSR, ARES, or KRS. We download the data automatically into one database.',
      draw_spiders: '2. Draws "Spiders"',
      draw_desc: 'Instead of reading long records, we generate an interactive graph. Instantly see connections to shell companies.',
      erp_conn: '3. ERP Integration',
      erp_desc: 'We connect directly to the client\'s ERP. If a supplier stops paying, our system sends an instant warning.',
      zero_dev_risk: 'Proof of Stability: Zero Dev Risk',
      tech_not_on_paper: 'Technology is not on paper, it is deployed in production.',
      qa_tests: 'Successful QA Tests',
      code_coverage: 'Code coverage 85%+ by tests',
      unfair_advantage: 'Unfair Advantage',
      typo_alg: 'The algorithm connects identities in V4 even with typos.',
      infra: 'Infrastructure',
      scalable_now: 'PostgreSQL, Redis cache. Scalable immediately.',
      erp_gem: 'ERP Integrations: Enterprise Gem',
      erp_deeper: 'Public registers do not contain everything. V4-Finstat goes deeper thanks to connection to accounting.',
      real_time_payments: 'Real-time payment analysis',
      cash_flow_tracking: 'Does the partner pay invoices on time? We monitor cash-flow and liabilities.',
      auto_webhooks: 'Automatic Warnings (Webhooks)',
      risk_score_alert: 'Notification if the risk score of a key supplier deteriorates.',
      ready_connectors: 'Ready Connectors',
      implementation_hours: 'Implementation takes hours. We create enormous "switching costs".',
      business_model: 'Business Model & Profitability',
      high_margin: 'B2B SaaS with high margin and minimal operating costs.',
      pro_plan: 'PRO',
      medium_firms: 'For medium-sized companies',
      biggest_growth: 'Biggest growth',
      logistics: 'For logistics',
      transactional: 'Transactional model',
      banks_insurance: 'For Banks & Insurance',
      op_margin: 'Operating Margin',
      target_arr: 'Target ARR (Year 2)',
      est_churn: 'Estimated Churn',
      legal_compliance: 'Legal & Compliance',
      bulletproof: 'Bulletproof Compliance',
      gdpr_interest: 'GDPR & Legitimate Interest',
      gdpr_desc: 'Data collection is protected by Art. 6(1)(f) of GDPR. We have "Right to erasure" implemented.',
      fair_use: 'Fair Use & Security',
      fair_use_desc: 'Scraping engine uses rotating proxies. We do not overload state servers.',
      disclaimer: 'Automatic Disclaimer',
      disclaimer_desc: 'Each graph cites sources. Exclusion of our legal liability for data.',
      legal_title: '100% Legal & Zero Risk',
      agressive_growth: 'V4-Finstat is designed for aggressive growth but is completely legally untouchable.',
      clean_table: 'We have implemented a complete custom system. With investment, you take a clean table.',
      roadmap: '12-Month Roadmap',
      series_a: 'Series A Dominance',
      investment_ask: 'Investment Requirement',
      potential_10x: 'Potential: 10x within 3 years',
      series_a_val: 'Equity in technology for Series A with valuation of 15M €',
      ready_product: 'Ready Product',
      investment_sales: 'Investment doesn\'t go into development. It goes purely into sales and rapid scaling.',
      scalable_monopoly: 'Scalable Monopoly',
      cross_border_monopoly: 'We create an unshakeable monopoly on cross-border risk analysis.',
      live_demo_btn: 'Proceed to Live Demo',
      enterprise_ready: 'Enterprise Ready',
      q1_title: 'Launch & Traction',
      q1_desc: '0-3 months. First 10 B2B contracts.',
      q2_title: 'V4 Expansion',
      q2_desc: '4-6 months. Market entry in PL and HU.',
      q3_title: 'AI Intelligence',
      q3_desc: '7-9 months. AI risk predictions of the partner.',
      q4_title: 'Series A Dominance',
      q4_desc: '10-12 months. Valuation 15M+ EUR.'
    },
    home: {
      label: 'PROJECTS / REPOSITORY / V5.0',
      heading: 'ENGINEERING \n THE FUTURE \n <span className="text-silver">OF THE WEB.</span>',
      description: 'SYSTEMATIC COLLECTION OF ADVANCED WEB IMPLEMENTATIONS AND AI-DRIVEN ARCHITECTURES, SYNTHESIZED FOR ELITE PERFORMANCE.',
      error_loading: 'Error loading projects',
      error_desc: 'Check your internet connection or API URL.'
    },
    projects_data: {
      v4_finstat_title: 'V4-Finstat',
      v4_finstat_tagline: 'Financial Standardization & Deployment',
      v4_finstat_desc: 'Standardizing Docker environments and namespace for financial data processing.',
      ico_atlas_title: 'ICO Atlas',
      ico_atlas_tagline: 'Crypto Market Intelligence',
      ico_atlas_desc: 'A comprehensive tracking platform for Initial Coin Offerings and market trends.',
      booking_buddy_title: 'Booking Buddy',
      booking_buddy_tagline: 'AI-Powered Travel Assistant',
      booking_buddy_desc: 'Personalized travel planning and booking optimization using AI.',
      dream_casino_title: 'The Dream Casino',
      dream_casino_tagline: 'Premium Gaming Experience',
      dream_casino_desc: 'Luxury online casino platform reconstructed with a focus on UX and security.',
      bizagent_title: 'BizAgent',
      bizagent_tagline: 'AI Business Assistant for Freelancers',
      bizagent_desc: 'Complete solution for invoices, expenses and accounting specifically designed for the Slovak market.',
      lumina_os_title: 'Lumina OS',
      lumina_os_tagline: 'Next-Gen Operating System',
      lumina_os_desc: 'A concept OS focusing on neural interfaces and adaptive UI design.',
      betauthority_title: 'BetAuthority',
      betauthority_tagline: 'European Casino Rankings',
      betauthority_desc: 'Comparison tool for online casinos and betting platforms with real-time data and fair terms.',
      neon_bloom_messenger_title: 'Neon Bloom Messenger',
      neon_bloom_messenger_tagline: 'Premium Communication Ecosystem',
      neon_bloom_messenger_desc: 'High-performance, privacy-focused communication platform built on Matrix protocol.',
      v4_finstat_v5_0_title: 'V4-Finstat v5.0',
      v4_finstat_v5_0_tagline: 'Enterprise Ready B2B SaaS',
      v4_finstat_v5_0_desc: 'SaaS software for B2B monitoring of companies in the V4 region.',
      rubberduck_space_title: 'RubberDuck.Space',
      rubberduck_space_tagline: 'AI-Powered Autonomous Code Analysis & Repair',
      rubberduck_space_desc: 'Autonomous code analysis and repair platform for modern engineering teams.'
    },
    ingestion: {
      tech_stack: 'Tech Stack',
      architecture: 'Architecture',
      market_intel: 'Market Intel',
      upload_zip: 'Upload ZIP (AI Analysis)',
      processing: 'Processing ZIP...',
      analyzing: 'AI Analyzing Codebase...',
      success: 'Project Successfully Ingested',
      refine: 'Refine Details',
      save: 'Save to Repository'
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('SK');

  useEffect(() => {
    const saved = localStorage.getItem('larsen_lang') as Language;
    if (saved) setLanguage(saved);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('larsen_lang', lang);
  };

  const t = (key: string, section: string = 'common'): string => {
    try {
      return (translations[language] as any)[section][key] || key;
    } catch {
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
